version: 2
jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:full
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
